spring:
  profiles:
    active: test

logging:
  level:
    root: warn
    LikeLion6.weeks2: info

custom:
  property:
    single: custom-property
    comlist: comma, sparated, list, to, value
    ncp:
      id: api-id
      key: api-key
      url: http://ncp.com/
# custom.property.single
# custom.property.comlist